<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
	public function run() {
		/**
		 * Creating admin user
		 */
		User::create([
            'first_name' => 'admin',
            'last_name' => 'pfe',
            'role' => 'admin',
            'email' => 'admin@pfeinsight.com',
            'password' => bcrypt('password')
        ]);

		$this->call([
			CompaniesSeeder::class,
			TechnologiesSeeder::class,
			TeachersSeeder::class,
			StudentsSeeder::class
		]);


	}

    public function runOld()
    {
        // \App\Models\User::factory(10)->create();
        User::create([
            'first_name' => 'admin',
            'last_name' => 'pfe',
            'role' => 'admin',
            'email' => 'admin@pfeinsight.com',
            'password' => bcrypt('password')
        ]);

        $users = [
            [
				'apogee' => '18007992',
				'first_name' => 'HAIFAE',
				'last_name' => 'EL MOUSSAOUI',
				'email' => 'haifae.elmoussaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18010233',
				'first_name' => 'HOUYAME',
				'last_name' => 'AIT ABBOU',
				'email' => 'houyame.aitabbou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006468',
				'first_name' => 'IKRAM',
				'last_name' => 'EL AAZAOUZI',
				'email' => 'ikram.elaazaouzi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18008029',
				'first_name' => 'AMAL',
				'last_name' => 'KHATTABI',
				'email' => 'amal.khattabi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17008796',
				'first_name' => 'DIOR',
				'last_name' => 'NDIAYE',
				'email' => 'dior.ndiaye@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17007548',
				'first_name' => 'MANAL',
				'last_name' => 'ZAOUI',
				'email' => 'manal.zaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006549',
				'first_name' => 'JIHAN',
				'last_name' => 'FENNIRI',
				'email' => 'jihan.fenniri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006953',
				'first_name' => 'CHAIMAA',
				'last_name' => 'R GUIBI',
				'email' => 'chaimaa.rguibi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19009650',
				'first_name' => 'YASSINE',
				'last_name' => 'BOUOUZM',
				'email' => 'yassine.bououzm@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000010',
				'first_name' => 'CHAIMAE',
				'last_name' => 'OUKECHI',
				'email' => 'chaimae.oukechi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18008290',
				'first_name' => 'HIBAT ALLAH',
				'last_name' => 'SADRAOUI',
				'email' => 'hibatallah.sadraoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008634',
				'first_name' => 'SALMA',
				'last_name' => 'LACHIA',
				'email' => 'salma.lachia@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000078',
				'first_name' => 'KELTOUM',
				'last_name' => 'SOUINIA',
				'email' => 'keltoum.souinia@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17007567',
				'first_name' => 'OUMNIA',
				'last_name' => 'BOUTRIG',
				'email' => 'oumnia.boutrig@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000037',
				'first_name' => 'MOHAMED ACHRAF',
				'last_name' => 'EL HANI',
				'email' => 'mohamedachraf.elhani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009005',
				'first_name' => 'FAHD',
				'last_name' => 'EL HAOUARI',
				'email' => 'fahd.elhaouari@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006852',
				'first_name' => 'RANIA',
				'last_name' => 'FRIKICH',
				'email' => 'rania.frikich@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000218',
				'first_name' => 'HAMZA',
				'last_name' => 'LAFDALI',
				'email' => 'hamza.lafdali@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007854',
				'first_name' => 'FATIMA EZZAHRA',
				'last_name' => 'OURAZZOUQ',
				'email' => 'fatimaezzahra.ourazzouq@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006965',
				'first_name' => 'KENZA',
				'last_name' => 'MAATI',
				'email' => 'kenza.maati@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007933',
				'first_name' => 'NOUHAILA',
				'last_name' => 'SMINA',
				'email' => 'nouhaila.smina@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007936',
				'first_name' => 'FARAH',
				'last_name' => 'ZOUHRI',
				'email' => 'farah.zouhri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004960',
				'first_name' => 'OUSSAMA',
				'last_name' => 'BENAYADA',
				'email' => 'oussama.benayada@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011104',
				'first_name' => 'NOURA',
				'last_name' => 'BIROUK',
				'email' => 'noura.birouk@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006335',
				'first_name' => 'RANIA',
				'last_name' => 'EL GHALI',
				'email' => 'rania.elghali@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004329',
				'first_name' => 'YAHIA',
				'last_name' => 'KANDIL',
				'email' => 'yahia.kandil@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007150',
				'first_name' => 'OUMAYMA',
				'last_name' => 'MASROUR',
				'email' => 'oumayma.masrour@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008627',
				'first_name' => 'NADA',
				'last_name' => 'KOURTAH',
				'email' => 'nada.kourtah@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011266',
				'first_name' => 'SOM-BE-WENDE',
				'last_name' => 'ZOUNGRANA YVES ALBAN',
				'email' => 'som-be-wende.zoungranayvesalban@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008604',
				'first_name' => 'SALMA',
				'last_name' => 'MOUGTAHIDI',
				'email' => 'salma.mougtahidi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008679',
				'first_name' => 'NOUHAILA',
				'last_name' => 'EL AISSI',
				'email' => 'nouhaila.elaissi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000036',
				'first_name' => 'IKHLASSE',
				'last_name' => 'OUARDI',
				'email' => 'ikhlasse.ouardi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000186',
				'first_name' => 'CHAIMAA',
				'last_name' => 'LAGHDIRI',
				'email' => 'chaimaa.laghdiri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011115',
				'first_name' => 'MOUAD',
				'last_name' => 'TIZIT',
				'email' => 'mouad.tizit@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000126',
				'first_name' => 'LAMYAE',
				'last_name' => 'ETTAIEK',
				'email' => 'lamyae.ettaiek@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009006',
				'first_name' => 'FATIMA',
				'last_name' => 'ESSAOUDI',
				'email' => 'fatima.essaoudi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017808',
				'first_name' => 'ADAM',
				'last_name' => 'GHALLOUDI',
				'email' => 'adam.ghalloudi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015880',
				'first_name' => 'ZAKARIAE',
				'last_name' => 'ELOMARI',
				'email' => 'zakariae.elomari@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20006692',
				'first_name' => 'OMAR',
				'last_name' => 'BOUAINE',
				'email' => 'omar.bouaine@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18010142',
				'first_name' => 'KOKO JEAN HUGUES',
				'last_name' => 'PIBA',
				'email' => 'kokojeanhugues.piba@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006732',
				'first_name' => 'HAJAR',
				'last_name' => 'RADI',
				'email' => 'hajar.radi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006469',
				'first_name' => 'ACHRAF',
				'last_name' => 'FETTOUKH',
				'email' => 'achraf.fettoukh@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000087',
				'first_name' => 'NADA',
				'last_name' => 'ZALLAFI',
				'email' => 'NADA.ZALLAFI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011053',
				'first_name' => 'EMILIE OLIVE',
				'last_name' => 'CHIKANDO SINOU',
				'email' => 'emilieolive.chikandosinou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17007639',
				'first_name' => 'AYA',
				'last_name' => 'EL MESBAHI',
				'email' => 'aya.elmesbahi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20011375',
				'first_name' => 'CHAIMAE',
				'last_name' => 'KHADDAM',
				'email' => 'chaimae.khaddam@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011064',
				'first_name' => 'ABDERRAHIM',
				'last_name' => 'EL HAMZAOUI',
				'email' => 'abderrahim.elhamzaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19007468',
				'first_name' => 'MOHAMED ABDELBASSET',
				'last_name' => 'RAKNI',
				'email' => 'mohamedabdelbasset.rakni@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000058',
				'first_name' => 'IMANE',
				'last_name' => 'DRIAI',
				'email' => 'imane.driai@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000086',
				'first_name' => 'HAMZA',
				'last_name' => 'TAZI',
				'email' => 'hamza.tazi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19012018',
				'first_name' => 'IMANE',
				'last_name' => 'JNIHA',
				'email' => 'imane.jniha@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008695',
				'first_name' => 'MOHAMMED',
				'last_name' => 'DRIOUICH',
				'email' => 'mohammed.driouich1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007012',
				'first_name' => 'HIBA',
				'last_name' => 'BENGELOUNE',
				'email' => 'hiba.bengeloune@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000169',
				'first_name' => 'MALAK',
				'last_name' => 'EL ABASSI',
				'email' => 'malak.elabassi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000095',
				'first_name' => 'MUSTAPHA',
				'last_name' => 'QANNOUF',
				'email' => 'mustapha.qannouf1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008684',
				'first_name' => 'HAMZA',
				'last_name' => 'SINAA',
				'email' => 'hamza.sinaa@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008663',
				'first_name' => 'TAHA',
				'last_name' => 'SAMIR',
				'email' => 'taha.samir@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004484',
				'first_name' => 'SALIM',
				'last_name' => 'ALIOUA',
				'email' => 'salim.alioua@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21011657',
				'first_name' => 'FATIMA',
				'last_name' => 'KENBOUCH',
				'email' => 'fatima.kenbouch@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017206',
				'first_name' => 'ZINEB',
				'last_name' => 'BENAIDA',
				'email' => 'zineb.benaida@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16000360',
				'first_name' => 'ISMAIL',
				'last_name' => 'AMARIR',
				'email' => 'ismail.amarir@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20000844',
				'first_name' => 'MAJDA',
				'last_name' => 'BELHAJ',
				'email' => 'majda.belhaj1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000041',
				'first_name' => 'DOUNIA',
				'last_name' => 'BENZIANE',
				'email' => 'dounia.benziane@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000187',
				'first_name' => 'LOUBNA',
				'last_name' => 'EL HAJJI',
				'email' => 'loubna.elhajji@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009387',
				'first_name' => 'IHSSANE',
				'last_name' => 'GHARBI',
				'email' => 'ihssane.gharbi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011034',
				'first_name' => 'NIZAR',
				'last_name' => 'ATAOUI',
				'email' => 'nizar.ataoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17008374',
				'first_name' => 'ZINEB NOHAILA',
				'last_name' => 'BARAKAT',
				'email' => 'zinebnohaila.barakat@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16003987',
				'first_name' => 'MOHAMMED',
				'last_name' => 'BENGHABRIT',
				'email' => 'mohammed.benghabrit@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000244',
				'first_name' => 'YOUSRA',
				'last_name' => 'BENSALIM',
				'email' => 'yousra.bensalim@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006986',
				'first_name' => 'MALAK',
				'last_name' => 'ELAJAJE',
				'email' => 'malak.elajaje@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006654',
				'first_name' => 'SALOUA',
				'last_name' => 'HADIRI',
				'email' => 'saloua.hadiri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16003897',
				'first_name' => 'SALMA',
				'last_name' => 'HANSALA',
				'email' => 'salma.hansala@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006221',
				'first_name' => 'ZINEB',
				'last_name' => 'KRAIA',
				'email' => 'zineb.kraia@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16004865',
				'first_name' => 'HAMZA',
				'last_name' => 'LAMSAOURI',
				'email' => 'hamza.lamsaouri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006694',
				'first_name' => 'NOUHAILA',
				'last_name' => 'TADGHOUTI',
				'email' => 'nouhaila.tadghouti@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000076',
				'first_name' => 'KHAOULA',
				'last_name' => 'OUAHI',
				'email' => 'khaoula.ouahi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006321',
				'first_name' => 'YOUNESS',
				'last_name' => 'ABOURRICHE',
				'email' => 'youness.abourriche@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004304',
				'first_name' => 'AYOUB',
				'last_name' => 'ALEM',
				'email' => 'ayoub.alem@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009968',
				'first_name' => 'SAFAE',
				'last_name' => 'EL GHABI',
				'email' => 'safae.elghabi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006800',
				'first_name' => 'ACHRAF',
				'last_name' => 'JALAL',
				'email' => 'achraf.jalal@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000029',
				'first_name' => 'HAJAR',
				'last_name' => 'LAHLOU',
				'email' => 'hajar.lahlou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007916',
				'first_name' => 'NARJIS',
				'last_name' => 'STITOU',
				'email' => 'narjis.stitou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000163',
				'first_name' => 'KHADIJA',
				'last_name' => 'ELMESSAOUDI',
				'email' => 'KHADIJA.ELMESSAOUDI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19002414',
				'first_name' => 'TAHA',
				'last_name' => 'BAHAMMOU',
				'email' => 'taha.bahammou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17007007',
				'first_name' => 'LATIFA',
				'last_name' => 'BOUDAD',
				'email' => 'latifa.boudad@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000243',
				'first_name' => 'HAMZA',
				'last_name' => 'CHABANA',
				'email' => 'hamza.chabana@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011043',
				'first_name' => 'NAJLAE',
				'last_name' => 'NOR',
				'email' => 'najlae.nor@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006833',
				'first_name' => 'OMAYMA',
				'last_name' => 'SAHLI',
				'email' => 'omayma.sahli@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011142',
				'first_name' => 'ILYAS',
				'last_name' => 'BAHNIF',
				'email' => 'ilyas.bahnif@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000081',
				'first_name' => 'CHARAF EDDINE',
				'last_name' => 'SOFIANE',
				'email' => 'charafeddine.sofiane@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19010973',
				'first_name' => 'YOUSSRA',
				'last_name' => 'RAIHANI',
				'email' => 'youssra.raihani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19010827',
				'first_name' => 'INASS',
				'last_name' => 'SAIDNI',
				'email' => 'inass.saidni@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000190',
				'first_name' => 'MANAL',
				'last_name' => 'BENSSABAHIA',
				'email' => 'manal.benssabahia@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000080',
				'first_name' => 'HABIBA',
				'last_name' => 'GAIZI',
				'email' => 'habiba.gaizi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006727',
				'first_name' => 'ABDELLAH',
				'last_name' => 'LAMZALZY',
				'email' => 'abdellah.lamzalzy@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017629',
				'first_name' => 'HOUSSAM',
				'last_name' => 'ELASSRAOUI',
				'email' => 'houssam.elassraoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015881',
				'first_name' => 'WIAM',
				'last_name' => 'JEBBOUR',
				'email' => 'wiam.jebbour@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015885',
				'first_name' => 'OUARDA',
				'last_name' => 'AGHRAZ',
				'email' => 'ouarda.aghraz@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006817',
				'first_name' => 'MINA',
				'last_name' => 'AGNAOU',
				'email' => 'mina.agnaou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20000857',
				'first_name' => 'OUMAIMA',
				'last_name' => 'CHLAGUE',
				'email' => 'oumaima.chlague@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000103',
				'first_name' => 'HOUDA',
				'last_name' => 'DAHBI',
				'email' => 'dahbi.houda@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006452',
				'first_name' => 'AOUS',
				'last_name' => 'EL HASSNAOUI',
				'email' => 'aous.elhassnaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006364',
				'first_name' => 'AHMED KHALIL',
				'last_name' => 'BENDEFA',
				'email' => 'ahmedkhalil.bendefa@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20006852',
				'first_name' => 'FATIMA-EZZAHRAE',
				'last_name' => 'CHTAIBI',
				'email' => 'fatima-ezzahrae.chtaibi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006385',
				'first_name' => 'EL HASSAN',
				'last_name' => 'ED-DARHRI',
				'email' => 'elhassan.eddarhri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006439',
				'first_name' => 'AYMAN',
				'last_name' => 'EL AMRANI',
				'email' => 'ayman.elamrani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000091',
				'first_name' => 'DOHA',
				'last_name' => 'JIRRARI',
				'email' => 'DOHA.JIRRARI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009590',
				'first_name' => 'AHMED AYMEN',
				'last_name' => 'MARRAKCHI',
				'email' => 'ahmedaymen.marrakchi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000199',
				'first_name' => 'MOHAMMED',
				'last_name' => 'NAJOUI',
				'email' => 'mohammed.najoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000197',
				'first_name' => 'ANAS',
				'last_name' => 'NASRI',
				'email' => 'anas.nasri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004061',
				'first_name' => 'OUMAIMA',
				'last_name' => 'SRAISAH',
				'email' => 'oumaima.sraisah@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17007004',
				'first_name' => 'MANAL',
				'last_name' => 'OUBELKACEM',
				'email' => 'manal.oubelkacem@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17007577',
				'first_name' => 'NIAMA',
				'last_name' => 'ABOULHASSANE',
				'email' => 'niama.aboulhassane@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16000109',
				'first_name' => 'OMAR',
				'last_name' => 'AKIL',
				'email' => 'omar.akil@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000188',
				'first_name' => 'KARIMA',
				'last_name' => 'BENDEROUACH',
				'email' => 'karima.benderouach@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005721',
				'first_name' => 'SOUKAINA',
				'last_name' => 'BENKIRANE',
				'email' => 'soukaina.benkirane@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004680',
				'first_name' => 'YASSINE',
				'last_name' => 'BENNANI',
				'email' => 'yassine.bennani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006134',
				'first_name' => 'ZINEB',
				'last_name' => 'BENTASSIL',
				'email' => 'zineb.bentassil@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004423',
				'first_name' => 'DOUAA',
				'last_name' => 'EL GHARBI',
				'email' => 'douaa.elgharbi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011252',
				'first_name' => 'NERKIETA NAFISSATOU',
				'last_name' => 'ZOETYANDE',
				'email' => 'nerkietanafissatou.zoetyande@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008618',
				'first_name' => 'IKRAM',
				'last_name' => 'ZENZOULI',
				'email' => 'ikram.zenzouli@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19007697',
				'first_name' => 'AYOUB',
				'last_name' => 'MOUSSAFI',
				'email' => 'ayoub.moussafi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19006950',
				'first_name' => 'SALMA',
				'last_name' => 'RAFILI',
				'email' => 'salma.rafili@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000053',
				'first_name' => 'MOUAD',
				'last_name' => 'BENALI',
				'email' => 'mouad.benali1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000168',
				'first_name' => 'LAMIAE',
				'last_name' => 'EL FAKER',
				'email' => 'lamiae.elfaker@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000066',
				'first_name' => 'OUMKALTOUM',
				'last_name' => 'MKADMI',
				'email' => 'oumkaltoum.mkadmi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000212',
				'first_name' => 'ABDELHAKIM',
				'last_name' => 'ALLALOU',
				'email' => 'abdelhakim.allalou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18010337',
				'first_name' => 'HALIMA',
				'last_name' => 'ATARRACHI',
				'email' => 'halima.atarrachi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011086',
				'first_name' => 'YASSINE',
				'last_name' => 'CHEMRIH',
				'email' => 'yassine.chemrih@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006305',
				'first_name' => 'ABDELMALEK',
				'last_name' => 'LOUDINI',
				'email' => 'abdelmalek.loudini@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017126',
				'first_name' => 'ANAS',
				'last_name' => 'ADRAOUI',
				'email' => 'anas.adraoui1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18010404',
				'first_name' => 'CHAIMAE',
				'last_name' => 'ELAZIZI',
				'email' => 'elazizi.chaimae@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18010332',
				'first_name' => 'ALAA-EDDINE',
				'last_name' => 'AZZI',
				'email' => 'alaaeddine.azzi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005819',
				'first_name' => 'IMANE',
				'last_name' => 'BENSAMDI',
				'email' => 'imane.bensamdi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006149',
				'first_name' => 'NERMINE',
				'last_name' => 'GHAZI',
				'email' => 'nermine.ghazi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011200',
				'first_name' => 'HIBA',
				'last_name' => 'BOUKHSSIBI',
				'email' => 'hiba.boukhssibi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006314',
				'first_name' => 'ZAHRA',
				'last_name' => 'EL JAAOUANI',
				'email' => 'zahra.eljaaouani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006970',
				'first_name' => 'RIHAB',
				'last_name' => 'MELHAOUI',
				'email' => 'rihab.melhaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011038',
				'first_name' => 'AMAL',
				'last_name' => 'OUKHRID',
				'email' => 'amal.oukhrid@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006687',
				'first_name' => 'ICHRAQ',
				'last_name' => 'TAYMOULI',
				'email' => 'ichraq.taymouli@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006870',
				'first_name' => 'CHAIMAE',
				'last_name' => 'TERFAS',
				'email' => 'chaimae.terfas@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '15006663',
				'first_name' => 'OUSSAMA',
				'last_name' => 'ZIAT',
				'email' => 'oussama.ziat@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011141',
				'first_name' => 'SALMA',
				'last_name' => 'MZALI',
				'email' => 'salma.mzali@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19010867',
				'first_name' => 'NADA',
				'last_name' => 'LAZHAR',
				'email' => 'nada.lazhar@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000192',
				'first_name' => 'KHAWLA',
				'last_name' => 'IDRI',
				'email' => 'khawla.idri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009966',
				'first_name' => 'HASNAA',
				'last_name' => 'EL HAJJI',
				'email' => 'hasnaa.elhajji@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007282',
				'first_name' => 'SOMIA',
				'last_name' => 'FAROUQ',
				'email' => 'somia.farouq@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000168',
				'first_name' => 'OUSSAMA',
				'last_name' => 'MEZOIR',
				'email' => 'oussama.mezoir@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015951',
				'first_name' => 'SARA',
				'last_name' => 'CHEGDANI',
				'email' => 'sara.chegdani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005812',
				'first_name' => 'OUAFAA',
				'last_name' => 'BENADDI',
				'email' => 'ouafaa.benaddi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006955',
				'first_name' => 'SOUKAINA',
				'last_name' => 'BOUGATTAYA',
				'email' => 'soukaina.bougattaya@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007311',
				'first_name' => 'YOUSRA',
				'last_name' => 'HASSINA',
				'email' => 'yousra.hassina@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005194',
				'first_name' => 'YASSER',
				'last_name' => 'MOUNTIJ',
				'email' => 'yasser.mountij@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000155',
				'first_name' => 'ASMAE',
				'last_name' => 'AQUIL',
				'email' => 'asmae.aquil@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004998',
				'first_name' => 'AYOUB',
				'last_name' => 'LAHMAMI',
				'email' => 'ayoub.lahmami@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005529',
				'first_name' => 'ISSAM',
				'last_name' => 'TABCHI',
				'email' => 'issam.tabchi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011023',
				'first_name' => 'MARWANE',
				'last_name' => 'BOUHADDOU',
				'email' => 'marwane.bouhaddou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19010961',
				'first_name' => 'YAHYA',
				'last_name' => 'MOUMNI',
				'email' => 'yahya.moumni@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19007233',
				'first_name' => 'SALMA',
				'last_name' => 'EL FEKAK',
				'email' => 'salma.elfekak@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19010041',
				'first_name' => 'OUMAIMA',
				'last_name' => 'SMINA',
				'email' => 'oumaima.smina@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008652',
				'first_name' => 'MARWA',
				'last_name' => 'BENKERROUM',
				'email' => 'marwa.benkerroum@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011119',
				'first_name' => 'FATIMA ZAHRA',
				'last_name' => 'ENAGRE',
				'email' => 'fatimazahra.enagre@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000147',
				'first_name' => 'BILAL',
				'last_name' => 'BOUTAHLI',
				'email' => 'bilal.boutahli@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000177',
				'first_name' => 'ASMAE',
				'last_name' => 'DAIBAZI',
				'email' => 'asmae.daibazi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000161',
				'first_name' => 'INTISSAR',
				'last_name' => 'OUETTAS',
				'email' => 'INTISSAR.OUETTAS@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18005018',
				'first_name' => 'AYOUB',
				'last_name' => 'AMAL',
				'email' => 'ayoub.amal@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18008065',
				'first_name' => 'SOUKAINA',
				'last_name' => 'EL AZHARY',
				'email' => 'soukaina.elazhary@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006355',
				'first_name' => 'HAMZA',
				'last_name' => 'BARGACH',
				'email' => 'hamza.bargach1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000194',
				'first_name' => 'MERYEM',
				'last_name' => 'BENSAID',
				'email' => 'MERYEM.BENSAID@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000099',
				'first_name' => 'SALMA',
				'last_name' => 'EL MRHARRAZ',
				'email' => 'SALMA.ELMRHARRAZ@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007427',
				'first_name' => 'SOUKAINA',
				'last_name' => 'ELAITARI',
				'email' => 'soukaina.elaitari@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007055',
				'first_name' => 'FATIMA',
				'last_name' => 'JARJER',
				'email' => 'fatima.jarjer@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009963',
				'first_name' => 'ISMAIL',
				'last_name' => 'YAHYAOUI',
				'email' => 'ismail.yahyaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000043',
				'first_name' => 'SARAH',
				'last_name' => 'AGGOUR',
				'email' => 'sarah.aggour@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18010603',
				'first_name' => 'NADA',
				'last_name' => 'ECH-CHOUQI',
				'email' => 'echchouqi.nada@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000006',
				'first_name' => 'NOUR-EL HOUDA',
				'last_name' => 'GUENDOULA',
				'email' => 'nour-elhouda.guendoula@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000099',
				'first_name' => 'FADI',
				'last_name' => 'IMANI',
				'email' => 'fadi.imani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000194',
				'first_name' => 'MERYEM',
				'last_name' => 'TOULALI',
				'email' => 'meryem.toulali@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000097',
				'first_name' => 'OMAR',
				'last_name' => 'KERCHAOUI',
				'email' => 'omar.kerchaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008615',
				'first_name' => 'SARA',
				'last_name' => 'LARROUSSI',
				'email' => 'sara.larroussi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006537',
				'first_name' => 'HAJAR',
				'last_name' => 'EL KHANFRI',
				'email' => 'hajar.elkhanfri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006518',
				'first_name' => 'KAWTAR',
				'last_name' => 'ES SEBBANI',
				'email' => 'kawtar.essebbani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011072',
				'first_name' => 'ILIASS',
				'last_name' => 'FOUKHAR',
				'email' => 'iliass.foukhar@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005847',
				'first_name' => 'AMINE',
				'last_name' => 'JARHNI',
				'email' => 'amine.jarhni@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17003784',
				'first_name' => 'MOUAD',
				'last_name' => 'KERDOUD',
				'email' => 'mouad.kerdoud@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006903',
				'first_name' => 'YASSINE',
				'last_name' => 'RHAZI',
				'email' => 'yassine.rhazi1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005468',
				'first_name' => 'EL MAHDI',
				'last_name' => 'SIDATE',
				'email' => 'elmahdi.sidate@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011156',
				'first_name' => 'ANASS',
				'last_name' => 'AIT EL KOUCH',
				'email' => 'anass.aitelkouch@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16004719',
				'first_name' => 'AMAL',
				'last_name' => 'ZEKRI',
				'email' => 'amal.zekri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007996',
				'first_name' => 'WAFAE',
				'last_name' => 'ABOUZBIBA',
				'email' => 'wafae.abouzbiba@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19010618',
				'first_name' => 'IMANE',
				'last_name' => 'BAHAMAD',
				'email' => 'imane.bahamad@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20005731',
				'first_name' => 'OUSSAMA',
				'last_name' => 'BEKRINE',
				'email' => 'oussama.bekrine@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006909',
				'first_name' => 'MERYEM',
				'last_name' => 'BOUTLANE',
				'email' => 'meryem.boutlane@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000193',
				'first_name' => 'MANAL',
				'last_name' => 'EL AMRANI',
				'email' => 'MANAL.ELAMRANI1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000167',
				'first_name' => 'MOHAMED',
				'last_name' => 'EL ATTAOUI',
				'email' => 'mohamed.elattaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006816',
				'first_name' => 'SAAD',
				'last_name' => 'MAZOUZI',
				'email' => 'saad.mazouzi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007869',
				'first_name' => 'MARYAM',
				'last_name' => 'OUMAMI',
				'email' => 'maryam.oumami@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20005505',
				'first_name' => 'EL MEHDI',
				'last_name' => 'SAFI',
				'email' => 'elmehdi.safi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16004931',
				'first_name' => 'MOHAMMED SAAD',
				'last_name' => 'TEBAA',
				'email' => 'mohammedsaad.tebaa@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009404',
				'first_name' => 'ZEINEBOU',
				'last_name' => 'VALL KHEIR',
				'email' => 'zeinebou.vallkheir@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000141',
				'first_name' => 'ANAS',
				'last_name' => 'ABOUSAADIA',
				'email' => 'anas.abousaadia@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000170',
				'first_name' => 'CHAIMAE',
				'last_name' => 'EL OUAHHABY',
				'email' => 'chaimae.elouahhaby@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000033',
				'first_name' => 'AHMED',
				'last_name' => 'FAHIM',
				'email' => 'ahmed.fahim@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19015220',
				'first_name' => 'KOSSI ELOLO BERNARD',
				'last_name' => 'DEKPE',
				'email' => 'kossielolobernard.dekpe@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19003672',
				'first_name' => 'MOHAMED',
				'last_name' => 'ZIRARI',
				'email' => 'mohamed.zirari@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006997',
				'first_name' => 'MOHAMED',
				'last_name' => 'BOUTAIB',
				'email' => 'mohamed.boutaib@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009494',
				'first_name' => 'MONTASSIR',
				'last_name' => 'BENJALLOUL',
				'email' => 'montassir.benjalloul1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19007144',
				'first_name' => 'AYOUB',
				'last_name' => 'OUDADA',
				'email' => 'ayoub.oudada@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000009',
				'first_name' => 'ADIL',
				'last_name' => 'SOUKAINI',
				'email' => 'adil.soukaini@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000088',
				'first_name' => 'HICHAM',
				'last_name' => 'TAIB',
				'email' => 'hicham.taib@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000035',
				'first_name' => 'ALI',
				'last_name' => 'ZNIBER',
				'email' => 'ali.zniber@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005162',
				'first_name' => 'OMAR',
				'last_name' => 'EL BADAOUI',
				'email' => 'omar.elbadaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17007831',
				'first_name' => 'AYMANE',
				'last_name' => 'EL MOUHTARIM',
				'email' => 'aymane.elmouhtarim@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005436',
				'first_name' => 'ABDELKHALEK',
				'last_name' => 'FAIK',
				'email' => 'abdelkhalek.faik@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005893',
				'first_name' => 'ABDENNOUR',
				'last_name' => 'JEBBAR',
				'email' => 'abdennour.jebbar@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17010439',
				'first_name' => 'GOLVEN CALIN',
				'last_name' => 'LOGMO ADMEO',
				'email' => 'golvencalin.logmoadmeo@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006980',
				'first_name' => 'WIAM',
				'last_name' => 'MOSSALLI',
				'email' => 'wiam.mossalli@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000158',
				'first_name' => 'RANIA',
				'last_name' => 'AIT HMADOUCH',
				'email' => 'RANIA.AITHMADOUCH@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000045',
				'first_name' => 'ZINEB',
				'last_name' => 'AIT MANSOUR',
				'email' => 'ZINEB.AITMANSOUR@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006791',
				'first_name' => 'SALMA',
				'last_name' => 'AL OUARDI',
				'email' => 'salma.alouardi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000024',
				'first_name' => 'YOUSRA',
				'last_name' => 'DDALLA',
				'email' => 'YOUSRA.DDALLA@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006294',
				'first_name' => 'AYOUB',
				'last_name' => 'EL GARAA',
				'email' => 'ayoub.elgaraa@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000215',
				'first_name' => 'MOHAMMED',
				'last_name' => 'EL YOUSFI-ALAOUI',
				'email' => 'MOHAMMED.ELYOUSFI-ALAOUI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000203',
				'first_name' => 'AYOUB',
				'last_name' => 'FADILI',
				'email' => 'AYOUB.FADILI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17007017',
				'first_name' => 'KENZA',
				'last_name' => 'IFKIRNE',
				'email' => 'kenza.ifkirne@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17000549',
				'first_name' => 'ABDERRAZZAK',
				'last_name' => 'GOUMIDI',
				'email' => 'abderrazzak.goumidi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20010521',
				'first_name' => 'IHSSAN',
				'last_name' => 'SAHMI',
				'email' => 'ihssan.sahmi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000176',
				'first_name' => 'IHSSANE',
				'last_name' => 'SARDI',
				'email' => 'IHSSANE.SARDI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008672',
				'first_name' => 'HASSAN AYOUB',
				'last_name' => 'BENASSER',
				'email' => 'hassanayoub.benasser@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000100',
				'first_name' => 'OUMAIMA',
				'last_name' => 'BENSAR',
				'email' => 'oumaima.bensar@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015271',
				'first_name' => 'MOHAMED',
				'last_name' => 'EL KHCHINE',
				'email' => 'mohamed.elkhchine1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015929',
				'first_name' => 'MASSINA',
				'last_name' => 'HAMMADI',
				'email' => 'massina.hammadi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000137',
				'first_name' => 'MOHAMED',
				'last_name' => 'LAGHRISSI',
				'email' => 'mohamed.laghrissi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000182',
				'first_name' => 'CHAIMAA',
				'last_name' => 'LOUADNI',
				'email' => 'chaimaa.louadni@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000077',
				'first_name' => 'SAFAA',
				'last_name' => 'LOUZAOUI',
				'email' => 'safaa.louzaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000063',
				'first_name' => 'MEHDI',
				'last_name' => 'OUGAAMOU',
				'email' => 'mehdi.mehdiougaamou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015770',
				'first_name' => 'ZAYNAB',
				'last_name' => 'ATIR',
				'email' => 'zaynab.atir@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005778',
				'first_name' => 'KAWTAR',
				'last_name' => 'BAKOUR',
				'email' => 'kawtar.bakour@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005831',
				'first_name' => 'YOUNESS',
				'last_name' => 'JABAR',
				'email' => 'youness.jabar@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16004718',
				'first_name' => 'SAFOUANE',
				'last_name' => 'LAMMARI',
				'email' => 'safouane.lammari@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009449',
				'first_name' => 'MAMINA',
				'last_name' => 'M KHAITIR CHIEKH',
				'email' => 'mamina.mkhaitirchiekh@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015938',
				'first_name' => 'IKRAM',
				'last_name' => 'AIT BELAID',
				'email' => 'ikram.aitbelaid@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20013993',
				'first_name' => 'AISSA',
				'last_name' => 'BAKHIL',
				'email' => 'aissa.bakhil@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000146',
				'first_name' => 'ABDELLAH',
				'last_name' => 'ALAOUI',
				'email' => 'ABDELLAH.ALAOUI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009015',
				'first_name' => 'MALIK',
				'last_name' => 'BERBACH',
				'email' => 'malik.berbach@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006400',
				'first_name' => 'MOHAMED',
				'last_name' => 'ECHTOUKI',
				'email' => 'mohamed.echtouki@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16000022',
				'first_name' => 'IMADEDDINE',
				'last_name' => 'EL AASSALI',
				'email' => 'imadeddine.elaassali@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007102',
				'first_name' => 'MOUNA',
				'last_name' => 'EL HAJJI',
				'email' => 'mouna.elhajji@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000062',
				'first_name' => 'CHAYMAA',
				'last_name' => 'ELHARTI',
				'email' => 'chaymaa.elharti@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000104',
				'first_name' => 'OUISSAL',
				'last_name' => 'ELKORRI',
				'email' => 'OUISSAL.ELKORRI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006665',
				'first_name' => 'OTHMANE',
				'last_name' => 'HANYF',
				'email' => 'othmane.hanyf@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20005536',
				'first_name' => 'SOUFIANE',
				'last_name' => 'JEMMAL',
				'email' => 'soufiane.jemmal@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004527',
				'first_name' => 'HAMZA',
				'last_name' => 'KADIMI',
				'email' => 'hamza.kadimi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009444',
				'first_name' => 'AKRAM',
				'last_name' => 'LAAMARTI',
				'email' => 'akram.laamarti@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17000543',
				'first_name' => 'ANASS',
				'last_name' => 'LAKTAIBI',
				'email' => 'anass.laktaibi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000184',
				'first_name' => 'YASSINE',
				'last_name' => 'OUJAA',
				'email' => 'yassine.oujaa@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007937',
				'first_name' => 'ZINEB',
				'last_name' => 'TIBARI',
				'email' => 'zineb.tibari@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18010184',
				'first_name' => 'ADRIANO',
				'last_name' => 'TIOTSOP FOGUE',
				'email' => 'adriano.tiotsopfogue@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000054',
				'first_name' => 'CHAYMA',
				'last_name' => 'TLEMCANI',
				'email' => 'CHAYMA.TLEMCANI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000157',
				'first_name' => 'YOUSSEF',
				'last_name' => 'EL-OTHMANI',
				'email' => 'youssef.el-othmani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000034',
				'first_name' => 'MOHAMED AMINE',
				'last_name' => 'EL KAABA',
				'email' => 'mohamedamine.elkaaba@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000151',
				'first_name' => 'ABDESSAMAD',
				'last_name' => 'BOUNASSEH',
				'email' => 'abdessamad.bounasseh@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000102',
				'first_name' => 'OUSSAMA',
				'last_name' => 'HMOUDAT',
				'email' => 'oussama.hmoudat@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000030',
				'first_name' => 'AYMANE',
				'last_name' => 'KABBA',
				'email' => 'aymane.kabba@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19007217',
				'first_name' => 'YOUNES',
				'last_name' => 'ACHAOUI',
				'email' => 'younes.achaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017281',
				'first_name' => 'HAMZA',
				'last_name' => 'MOUHAOUIR',
				'email' => 'hamza.mouhaouir@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20000307',
				'first_name' => 'NIMA',
				'last_name' => 'M\'HIN',
				'email' => 'nima.mhin@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017537',
				'first_name' => 'IKRAM',
				'last_name' => 'TAHER',
				'email' => 'ikram.taher@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015883',
				'first_name' => 'KHADIJA',
				'last_name' => 'LAATITINE',
				'email' => 'khadija.laatitine@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015868',
				'first_name' => 'HASSAN',
				'last_name' => 'MEZIANE ZERHOUNI',
				'email' => 'hassan.mezianezerhouni@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000015',
				'first_name' => 'YASSINE',
				'last_name' => 'OUSSI',
				'email' => 'yassine.oussi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000098',
				'first_name' => 'WASSIM',
				'last_name' => 'RIFAY',
				'email' => 'wassim.rifay@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011102',
				'first_name' => 'HAMZA',
				'last_name' => 'BENJELLOUN',
				'email' => 'hamza.benjelloun@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005414',
				'first_name' => 'ISMAIL',
				'last_name' => 'EL FEKAK',
				'email' => 'ismail.elfekak@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006533',
				'first_name' => 'CHAIMAE',
				'last_name' => 'SAFRAOUI',
				'email' => 'chaimae.safraoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16000050',
				'first_name' => 'AYOUB',
				'last_name' => 'EL HALABI',
				'email' => 'ayoub.elhalabi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000081',
				'first_name' => 'MAROUA',
				'last_name' => 'EL AZZAOUI',
				'email' => 'MAROUA.ELAZZAOUI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000047',
				'first_name' => 'IMANE',
				'last_name' => 'EL BAKKOURI',
				'email' => 'IMANE.ELBAKKOURI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17003110',
				'first_name' => 'HAJAR',
				'last_name' => 'FAIZ',
				'email' => 'hajar.faiz@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17000711',
				'first_name' => 'HIND',
				'last_name' => 'GLIOULA',
				'email' => 'hind.glioula@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007169',
				'first_name' => 'NISRINE',
				'last_name' => 'MOFAKIR',
				'email' => 'nisrine.mofakir@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19007523',
				'first_name' => 'YASMINE',
				'last_name' => 'ESSALMANI',
				'email' => 'yasmine.essalmani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008711',
				'first_name' => 'FAYCAL',
				'last_name' => 'EL OURRAT',
				'email' => 'faycal.elourrat@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21015519',
				'first_name' => 'AYMANE',
				'last_name' => 'BITI',
				'email' => 'aymane.biti@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21011748',
				'first_name' => 'ZAKARIAE',
				'last_name' => 'SAIDI',
				'email' => 'zakariae.saidi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017855',
				'first_name' => 'KHAOULA',
				'last_name' => 'LAZAAR',
				'email' => 'khaoula.lazaar@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000061',
				'first_name' => 'NOUHAILA',
				'last_name' => 'MOUAD',
				'email' => 'nouhaila.mouad@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19006997',
				'first_name' => 'MEHDI',
				'last_name' => 'MOUSSADIK',
				'email' => 'mehdi.moussadik@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008673',
				'first_name' => 'YASSINE',
				'last_name' => 'OUBENMOH',
				'email' => 'yassine.oubenmoh@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008915',
				'first_name' => 'MAROUANE',
				'last_name' => 'QAFFSSAOUI',
				'email' => 'marouane.qaffssaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000127',
				'first_name' => 'GHIZLANE',
				'last_name' => 'EL HIRECH',
				'email' => 'ghizlane.elhirech@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005227',
				'first_name' => 'SAAD',
				'last_name' => 'ERRAZGOUNI',
				'email' => 'saad.errazgouni@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005686',
				'first_name' => 'ANAS',
				'last_name' => 'HILIA',
				'email' => 'anas.hilia@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005624',
				'first_name' => 'ABDELLAH',
				'last_name' => 'HMADE',
				'email' => 'abdellah.hmade@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005155',
				'first_name' => 'TAHA',
				'last_name' => 'LAHRIZI',
				'email' => 'taha.lahrizi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006848',
				'first_name' => 'KAWTAR',
				'last_name' => 'MOULAHID',
				'email' => 'kawtar.moulahid@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006940',
				'first_name' => 'OMAR',
				'last_name' => 'MOUSTAHIB',
				'email' => 'omar.moustahib@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006481',
				'first_name' => 'OUMAIMA',
				'last_name' => 'SAFI',
				'email' => 'oumaima.safi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008624',
				'first_name' => 'MERYEM',
				'last_name' => 'AIT OUAKRIM',
				'email' => 'meryem.aitouakrim@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006772',
				'first_name' => 'ASMAE',
				'last_name' => 'ASSMOUGUE',
				'email' => 'asmae.assmougue@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005975',
				'first_name' => 'KAWTAR',
				'last_name' => 'BEKKALI',
				'email' => 'kawtar.bekkali@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007440',
				'first_name' => 'MOHAMED',
				'last_name' => 'BELLAALA',
				'email' => 'mohamed.bellaala@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007124',
				'first_name' => 'MANAL',
				'last_name' => 'EL GUEROUANI',
				'email' => 'manal.elguerouani1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000008',
				'first_name' => 'ATIKA',
				'last_name' => 'EL HAOUARI',
				'email' => 'ATIKA.ELHAOUARI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006457',
				'first_name' => 'OMAR',
				'last_name' => 'EL MEKKAOUI',
				'email' => 'omar.elmekkaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007070',
				'first_name' => 'OUMAIMA',
				'last_name' => 'EL MOUJOUDI',
				'email' => 'oumaima.elmoujoudi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007304',
				'first_name' => 'IKRAME',
				'last_name' => 'HAYTOM',
				'email' => 'ikrame.haytom@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000183',
				'first_name' => 'AYOUB',
				'last_name' => 'KASSI',
				'email' => 'AYOUB.KASSI@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000052',
				'first_name' => 'RHITA',
				'last_name' => 'TIGRIOUI',
				'email' => 'rhita.tigrioui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000179',
				'first_name' => 'AIMEN',
				'last_name' => 'ZEROUAL',
				'email' => 'aimen.zeroual@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19008666',
				'first_name' => 'CHAYMAA',
				'last_name' => 'AHCINE',
				'email' => 'chaymaa.ahcine@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19010967',
				'first_name' => 'HIND',
				'last_name' => 'BRIBRI',
				'email' => 'hind.bribri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011462',
				'first_name' => 'KENZA',
				'last_name' => 'BELHAJ-SOULAMI',
				'email' => 'kenza.belhaj-soulami@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017268',
				'first_name' => 'YASMINE',
				'last_name' => 'KAMI',
				'email' => 'yasmine.kami@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011062',
				'first_name' => 'HOUSSAM',
				'last_name' => 'MERIZAK',
				'email' => 'houssam.merizak@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000013',
				'first_name' => 'MOHAMED SAAD',
				'last_name' => 'OHASSAN',
				'email' => 'mohamedsaad.ohassan@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004777',
				'first_name' => 'HASSAN',
				'last_name' => 'BERRAGRAGUI',
				'email' => 'hassan.berragragui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17008695',
				'first_name' => 'AHMED MAHMOUD',
				'last_name' => 'EBOU EL HASSANI',
				'email' => 'ahmedmahmoud.ebouelhassani@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000218',
				'first_name' => 'OMAYMA',
				'last_name' => 'FRIAIN',
				'email' => 'omayma.friain@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18009497',
				'first_name' => 'OUSSAMA',
				'last_name' => 'AZIZ',
				'email' => 'oussama.aziz@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19011058',
				'first_name' => 'HAYTAM',
				'last_name' => 'BARIK',
				'email' => 'haytam.barik@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18006624',
				'first_name' => 'AYMEN',
				'last_name' => 'FANNOUCH',
				'email' => 'aymen.fannouch@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007157',
				'first_name' => 'CHAIMAE',
				'last_name' => 'MOUMNI',
				'email' => 'chaimae.moumni@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000141',
				'first_name' => 'ILHAM',
				'last_name' => 'OUKASSOU',
				'email' => 'ILHAM.OUKASSOU@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000111',
				'first_name' => 'ABIR',
				'last_name' => 'ZAHI',
				'email' => 'abir.zahi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20012111',
				'first_name' => 'IBTISSAM',
				'last_name' => 'ZEROUALI',
				'email' => 'ibtissam.zerouali@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000025',
				'first_name' => 'NOUHAILA',
				'last_name' => 'ZIYANE',
				'email' => 'nouhaila.ziyane@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18007488',
				'first_name' => 'LINA',
				'last_name' => 'ZIZI',
				'email' => 'lina.zizi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000049',
				'first_name' => 'NAJWA',
				'last_name' => 'BERRAS',
				'email' => 'najwa.berras@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000056',
				'first_name' => 'SOUKAINA',
				'last_name' => 'DELLALE',
				'email' => 'soukaina.dellale@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000018',
				'first_name' => 'OMAR',
				'last_name' => 'DEFAOUI',
				'email' => 'omar.defaoui@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017620',
				'first_name' => 'MOHAMED',
				'last_name' => 'JALAL',
				'email' => 'mohamed.jalal1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017117',
				'first_name' => 'MOHAMMED',
				'last_name' => 'GHOUMMAID',
				'email' => 'mohammed.ghoummaid@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017854',
				'first_name' => 'ANASS',
				'last_name' => 'CHAGRI',
				'email' => 'anass.chagri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17009577',
				'first_name' => 'MAWUFEMO JOSUE',
				'last_name' => 'ABOU',
				'email' => 'mawufemo.abou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16000234',
				'first_name' => 'LEILA',
				'last_name' => 'ELHADIOUIA',
				'email' => 'leila.elhadiouia@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005215',
				'first_name' => 'AHMED',
				'last_name' => 'ELKHDADI',
				'email' => 'ahmed.elkhdadi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000217',
				'first_name' => 'IMAN',
				'last_name' => 'FRIAIN',
				'email' => 'iman.friain@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006198',
				'first_name' => 'SALMA',
				'last_name' => 'GOUZA',
				'email' => 'salma.gouza@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17007030',
				'first_name' => 'IBTISSAM',
				'last_name' => 'NOUMA',
				'email' => 'ibtissam.nouma@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005242',
				'first_name' => 'ZAKARIA',
				'last_name' => 'OUADRHIRI IDRISSI AZZOUZI',
				'email' => 'zakaria.ouadrhiriidrissiazzouzi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000157',
				'first_name' => 'OUMAIMA',
				'last_name' => 'AOUZAL',
				'email' => 'oumaima.aouzal@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20012117',
				'first_name' => 'ZIYAD',
				'last_name' => 'BOUSSERRHINE',
				'email' => 'ziyad.bousserrhine@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000205',
				'first_name' => 'ZAKARIA',
				'last_name' => 'EL HADY',
				'email' => 'ZAKARIA.ELHADY@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18004591',
				'first_name' => 'NIZAR',
				'last_name' => 'STITOU',
				'email' => 'nizar.stitou@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18000173',
				'first_name' => 'YOUSSEF',
				'last_name' => 'ZAHI',
				'email' => 'YOUSSEF.ZAHI1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000047',
				'first_name' => 'ABDELJALIL',
				'last_name' => 'FENNIRI',
				'email' => 'abdeljalil.fenniri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000167',
				'first_name' => 'MERYEM',
				'last_name' => 'EL HASSOUNI',
				'email' => 'meryem.elhassouni1@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000145',
				'first_name' => 'OMAR',
				'last_name' => 'BENOUAHI',
				'email' => 'omar.benouahi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000191',
				'first_name' => 'NASSIMA',
				'last_name' => 'JEBBAR',
				'email' => 'nassima.jebbar@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000037',
				'first_name' => 'ANAS',
				'last_name' => 'BENZEKRI',
				'email' => 'anas.anasbenzekri@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20000852',
				'first_name' => 'YAHYA',
				'last_name' => 'LBARRAH',
				'email' => 'yahya.lbarrah@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18010496',
				'first_name' => 'SANAE',
				'last_name' => 'OUBAHASSOU',
				'email' => 'oubahassou.sanae@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '21017164',
				'first_name' => 'HOUSSAM EDDINE',
				'last_name' => 'ABOU EL HAOUL',
				'email' => 'houssameddine.abouelhaoul@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '16000086',
				'first_name' => 'ISMAIL',
				'last_name' => 'ARZIKI',
				'email' => 'ismail.arziki@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005537',
				'first_name' => 'YOUSSEF',
				'last_name' => 'ZEAIKOR',
				'email' => 'youssef.zeaikor@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19007215',
				'first_name' => 'AHMED TAHA',
				'last_name' => 'MOTASSIM',
				'email' => 'ahmedtaha.motassim@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '19000067',
				'first_name' => 'OUSSAMA',
				'last_name' => 'SAAD',
				'email' => 'oussama.saad@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '20000861',
				'first_name' => 'SOUHAIL',
				'last_name' => 'EL MRIHY',
				'email' => 'souhail.elmrihy@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '18002375',
				'first_name' => 'TAOUFIK',
				'last_name' => 'FRIHAT',
				'email' => 'taoufik.frihat@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17004178',
				'first_name' => 'ABDELLAH',
				'last_name' => 'AZZOUZI',
				'email' => 'abdellah.azzouzi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005934',
				'first_name' => 'ASSMA',
				'last_name' => 'BENKADDOUR',
				'email' => 'assma.benkaddour@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005256',
				'first_name' => 'MOHSINE',
				'last_name' => 'EL OUARTITI',
				'email' => 'mohsine.elouartiti@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17005269',
				'first_name' => 'HAMZA',
				'last_name' => 'ELHARSI',
				'email' => 'hamza.elharsi@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006391',
				'first_name' => 'SALMA',
				'last_name' => 'MRABET',
				'email' => 'salma.mrabet@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '17006550',
				'first_name' => 'OUMAIMA',
				'last_name' => 'SABER',
				'email' => 'oumaima.saber@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],
			[
				'apogee' => '14000130',
				'first_name' => 'SAAD',
				'last_name' => 'SAHRAOUI DOUKKALI',
				'email' => 'saad.sahraouidoukkali@uit.ac.ma',
				'password' => bcrypt('password'),
				'role' => 'student',
			],


            // profs
            [
                'first_name' => 'BOUMAZZOU',
                'last_name' => 'Ibrahim',
                'email' => 'ibrahim.boumazzou@uit.ac.ma',
                'password' => bcrypt('password'),
                'role' => 'professor',
            ],
            [
                    'first_name' => 'ABOUTAFAIL',
                    'last_name' => 'Moulay Othman',
                    'email' => 'moulayothman.aboutafail@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'HMINA',
                    'last_name' => 'Nabil',
                    'email' => 'nabil.hmina@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'MHARZI',
                    'last_name' => 'Hassan',
                    'email' => 'h.mharzi@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'GRETETE',
                    'last_name' => 'Driss',
                    'email' => 'driss.gretete@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'MASLOUHI',
                    'last_name' => 'Mostafa',
                    'email' => 'mostafa.maslouhi@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'ABOUABDELLAH',
                    'last_name' => 'Abdellah',
                    'email' => 'abdellah.abouabdellah@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'BELGHITI',
                    'last_name' => 'Moulay Taib',
                    'email' => 'moulaytaib.belghiti@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'CHAOUI',
                    'last_name' => 'Habiba',
                    'email' => 'habiba.chaoui@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'ELOUADI',
                    'last_name' => 'Abdelmajid',
                    'email' => 'abdelmajid.elouadi@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'EL HAMI',
                    'last_name' => 'Norelislam',
                    'email' => 'norelislam.elhami@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'BENTALEB',
                    'last_name' => 'Youssef',
                    'email' => 'youssef.bentaleb@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'CHOUGDALI',
                    'last_name' => 'Khalid',
                    'email' => 'khalid.chougdali@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'BELFKIH',
                    'last_name' => 'Samir',
                    'email' => 'samir.belfkih@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'OUMAIRA',
                    'last_name' => 'Ilham',
                    'email' => 'ilham.oumaira@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'AMINE',
                    'last_name' => 'Aouatif',
                    'email' => 'aouatif.amine@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'BOUAYAD',
                    'last_name' => 'Anas',
                    'email' => 'anas.bouayad@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'EL BOUZEKRI EL IDRISSI',
                    'last_name' => 'Younes',
                    'email' => 'y.elbouzekri@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'AIT LAHCEN',
                    'last_name' => 'Ayoub',
                    'email' => 'ayoub.aitlahcen@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'HACHIMI',
                    'last_name' => 'Hanaa',
                    'email' => 'hanaa.hachimi@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'BANNARI',
                    'last_name' => 'Rachid',
                    'email' => 'rachid.bannari@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'MABTOUL',
                    'last_name' => 'Samira',
                    'email' => 'samira.mabtoul@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ],
            [
                    'first_name' => 'EL ABBADI',
                    'last_name' => 'Laila',
                    'email' => 'laila.elabbadi@uit.ac.ma',
                    'password' => bcrypt('password'),
                    'role' => 'professor',
            ]
        ];

        
        foreach ($users as $u) {
            $uu = User::create([
                'first_name' => $u['first_name'],
                'last_name' => $u['last_name'],
                'role' => $u['role'],
                'email' => $u['email'],
                'password' => $u['password'],
            ]);
            $uu->profile()->create($u['role'] == 'student' ? [
                'apogee' => $u['apogee']
            ] : []);

        }

    }
}
